services:
  rodeo:
    build:
      context: .
      args:
        WHISPER_MODEL: base.en
    container_name: rodeo
    environment:
      RODEO_ALLOWED_HOSTS: '["127.0.0.1", "localhost"]'
      RODEO_TIMEZONE: America/New_York
      RODEO_PUBLIC_URL: http://127.0.0.1:8000
    ports:
      - "127.0.0.1:8000:8000"
    restart: unless-stopped
    volumes:
      - ./data:/data
