"""Shared loader for the cross-engine parity fixture.

``tests/fixtures/dashboard-parity.json`` is generated by
``frontend/scripts/dump-dashboard-fixtures.ts`` and records what the
TypeScript engine in ``frontend/src/lib/dashboard.ts`` produces. This module
translates those cases into the Python engine's input types so both the parity
tests and the golden-snapshot script read the fixture the same way.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Any

from rodeo.services.scheduling import (
    AttemptOutcome,
    Difficulty,
    SchedulingAttempt,
)

FIXTURES_DIR = Path(__file__).parent / "fixtures"
PARITY_FIXTURE = FIXTURES_DIR / "dashboard-parity.json"
GOLDEN_FIXTURE = FIXTURES_DIR / "engine-v2-golden.json"


@dataclass(frozen=True, slots=True)
class ParityCase:
    name: str
    attempts: tuple[SchedulingAttempt, ...]
    expected: dict[str, Any]


@dataclass(frozen=True, slots=True)
class ParityFixture:
    timezone: str
    now: datetime
    problem_ids: frozenset[int]
    cases: tuple[ParityCase, ...]


def load_parity_fixture() -> ParityFixture:
    raw = json.loads(PARITY_FIXTURE.read_text())
    difficulty_by_problem = {
        problem["id"]: Difficulty(problem["difficulty"]) for problem in raw["problems"]
    }

    def to_attempt(row: dict[str, Any]) -> SchedulingAttempt:
        return SchedulingAttempt(
            problem_id=row["problemId"],
            attempt_id=row["id"],
            completed_at=datetime.fromisoformat(
                row["completedAt"].replace("Z", "+00:00")
            ),
            outcome=AttemptOutcome(row["outcome"]),
            duration_seconds=row.get("durationSeconds", row["durationMinutes"] * 60),
            difficulty=difficulty_by_problem.get(row["problemId"], Difficulty.MEDIUM),
        )

    return ParityFixture(
        timezone=raw["timezone"],
        now=datetime.fromisoformat(raw["now"]),
        problem_ids=frozenset(difficulty_by_problem),
        cases=tuple(
            ParityCase(
                name=name,
                attempts=tuple(to_attempt(row) for row in case["attempts"]),
                expected=case["expected"],
            )
            for name, case in raw["cases"].items()
        ),
    )
