/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live */
        get: operations["live_api_v1_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_api_v1_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Capabilities */
        get: operations["capabilities_api_v1_capabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/backups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Backup Status */
        get: operations["backup_status_api_v1_system_backups_get"];
        put?: never;
        /** Backup Now */
        post: operations["backup_now_api_v1_system_backups_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/backups/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore Backup */
        post: operations["restore_backup_api_v1_system_backups_restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/backups/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Backup Files */
        get: operations["backup_files_api_v1_system_backups_files_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/backups/files/{filename}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Backup */
        delete: operations["remove_backup_api_v1_system_backups_files__filename__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/prompt-templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Prompt Templates */
        get: operations["prompt_templates_api_v1_settings_prompt_templates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/prompt-templates/{template_key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Save Prompt Template */
        put: operations["save_prompt_template_api_v1_settings_prompt_templates__template_key__put"];
        post?: never;
        /** Reset Saved Prompt Template */
        delete: operations["reset_saved_prompt_template_api_v1_settings_prompt_templates__template_key__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/interview-goals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Interview Goals */
        get: operations["interview_goals_api_v1_settings_interview_goals_get"];
        /** Save Interview Goals */
        put: operations["save_interview_goals_api_v1_settings_interview_goals_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Data */
        get: operations["export_data_api_v1_system_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/clear": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Clear Data */
        post: operations["clear_data_api_v1_system_clear_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/problems": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Problems */
        get: operations["problems_api_v1_problems_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/problems/{problem_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Problem */
        get: operations["problem_api_v1_problems__problem_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/attempts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Attempts */
        get: operations["read_attempts_api_v1_attempts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/problems/{problem_id}/attempts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Problem Attempts */
        get: operations["read_problem_attempts_api_v1_problems__problem_id__attempts_get"];
        put?: never;
        /** Create Problem Attempt */
        post: operations["create_problem_attempt_api_v1_problems__problem_id__attempts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/attempts/{attempt_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Attempt */
        get: operations["read_attempt_api_v1_attempts__attempt_id__get"];
        put?: never;
        post?: never;
        /** Remove Attempt */
        delete: operations["remove_attempt_api_v1_attempts__attempt_id__delete"];
        options?: never;
        head?: never;
        /** Patch Attempt */
        patch: operations["patch_attempt_api_v1_attempts__attempt_id__patch"];
        trace?: never;
    };
    "/api/v1/attempts/{attempt_id}/recording": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Attempt Recording */
        delete: operations["remove_attempt_recording_api_v1_attempts__attempt_id__recording_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/catalog/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_api_v1_catalog_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Dashboard */
        get: operations["read_dashboard_api_v1_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/review-queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Review Queue */
        get: operations["review_queue_api_v1_review_queue_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read */
        get: operations["read_api_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/practice-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start */
        post: operations["start_api_v1_practice_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/practice-sessions/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current */
        get: operations["current_api_v1_practice_sessions_current_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/practice-sessions/{session_id}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pause */
        post: operations["pause_api_v1_practice_sessions__session_id__pause_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/practice-sessions/{session_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume */
        post: operations["resume_api_v1_practice_sessions__session_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/practice-sessions/{session_id}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop */
        post: operations["stop_api_v1_practice_sessions__session_id__stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/practice-sessions/{session_id}/finalize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Finalize */
        post: operations["finalize_api_v1_practice_sessions__session_id__finalize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/practice-sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Discard */
        delete: operations["discard_api_v1_practice_sessions__session_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/recordings/{recording_id}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Content */
        get: operations["content_api_v1_recordings__recording_id__content_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/attempts/{attempt_id}/transcription": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read */
        get: operations["read_api_v1_attempts__attempt_id__transcription_get"];
        put?: never;
        /** Create */
        post: operations["create_api_v1_attempts__attempt_id__transcription_post"];
        delete?: never;
        options?: never;
        head?: never;
        /** Correct */
        patch: operations["correct_api_v1_attempts__attempt_id__transcription_patch"];
        trace?: never;
    };
    "/api/v1/attempts/{attempt_id}/transcription/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry */
        post: operations["retry_api_v1_attempts__attempt_id__transcription_retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActivityDay */
        ActivityDay: {
            /** Key */
            key: string;
            /** Minutes */
            minutes: number;
            /** Problem Count */
            problem_count: number;
            /** Activity Level */
            activity_level: number;
        };
        /**
         * AttemptBlocker
         * @enum {string}
         */
        AttemptBlocker: "none" | "pattern" | "edge-cases" | "complexity" | "implementation" | "debugging" | "time";
        /** AttemptCreate */
        AttemptCreate: {
            /**
             * Completed At
             * Format: date-time
             */
            completed_at: string;
            /** Duration Seconds */
            duration_seconds: number;
            outcome: components["schemas"]["AttemptOutcome"];
            effort: components["schemas"]["AttemptEffort"];
            /** @default none */
            blocker: components["schemas"]["AttemptBlocker"];
            /**
             * Notes
             * @default
             */
            notes: string;
        };
        /**
         * AttemptEffort
         * @enum {string}
         */
        AttemptEffort: "light" | "moderate" | "heavy" | "brutal";
        /** AttemptListResponse */
        AttemptListResponse: {
            /** Items */
            items: components["schemas"]["AttemptResponse"][];
            /** Total */
            total: number;
            /** Offset */
            offset: number;
            /** Limit */
            limit: number;
        };
        /**
         * AttemptOutcome
         * @enum {string}
         */
        AttemptOutcome: "optimal" | "hint" | "solution" | "failed";
        /** AttemptResponse */
        AttemptResponse: {
            /** Id */
            id: string;
            /** Problem Id */
            problem_id: number;
            /** Practice Session Id */
            practice_session_id: string | null;
            /**
             * Completed At
             * Format: date-time
             */
            completed_at: string;
            /** Duration Seconds */
            duration_seconds: number;
            problem_difficulty_at_attempt: components["schemas"]["Difficulty"] | null;
            /** Target Minutes At Attempt */
            target_minutes_at_attempt?: number | null;
            outcome: components["schemas"]["AttemptOutcome"];
            effort: components["schemas"]["AttemptEffort"];
            blocker: components["schemas"]["AttemptBlocker"];
            /** Notes */
            notes: string;
            /** Recording Id */
            recording_id: string | null;
            /** Transcription Id */
            transcription_id: string | null;
            transcription_status: components["schemas"]["TranscriptionStatus"] | null;
            /** Has Audio */
            has_audio: boolean;
            /** Has Transcript */
            has_transcript: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** AttemptUpdate */
        AttemptUpdate: {
            /** Completed At */
            completed_at?: string | null;
            /** Duration Seconds */
            duration_seconds?: number | null;
            outcome?: components["schemas"]["AttemptOutcome"] | null;
            effort?: components["schemas"]["AttemptEffort"] | null;
            blocker?: components["schemas"]["AttemptBlocker"] | null;
            /** Notes */
            notes?: string | null;
        };
        /** BackupFile */
        BackupFile: {
            /** Filename */
            filename: string;
            /** Size Bytes */
            size_bytes: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Attempt Count */
            attempt_count?: number | null;
            /** Solved Count */
            solved_count?: number | null;
        };
        /** BackupFileListResponse */
        BackupFileListResponse: {
            /** Location */
            location: string;
            /** Recording Count */
            recording_count: number;
            /** Files */
            files: components["schemas"]["BackupFile"][];
        };
        /** BackupStatusResponse */
        BackupStatusResponse: {
            /** Enabled */
            enabled: boolean;
            /** Last Backup At */
            last_backup_at: string | null;
            /** Next Backup At */
            next_backup_at: string | null;
            /** Last Backup Filename */
            last_backup_filename: string | null;
            /** Snapshot Count */
            snapshot_count: number;
            /** Recordings Included */
            recordings_included: boolean;
            /** Location */
            location: string;
        };
        /** Body_stop_api_v1_practice_sessions__session_id__stop_post */
        Body_stop_api_v1_practice_sessions__session_id__stop_post: {
            /** Audio */
            audio?: string | null;
        };
        /** CapabilitiesResponse */
        CapabilitiesResponse: {
            transcription: components["schemas"]["TranscriptionCapability"];
        };
        /** CatalogSyncResponse */
        CatalogSyncResponse: {
            /** Id */
            id: string;
            status: components["schemas"]["CatalogSyncStatus"];
            /** Source */
            source: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Completed At */
            completed_at: string | null;
            /** Added Count */
            added_count: number;
            /** Updated Count */
            updated_count: number;
            /** Deactivated Count */
            deactivated_count: number;
            /** Error Code */
            error_code: string | null;
            /** Error Message */
            error_message: string | null;
        };
        /**
         * CatalogSyncStatus
         * @enum {string}
         */
        CatalogSyncStatus: "running" | "completed" | "failed";
        /** ClearResponse */
        ClearResponse: {
            /** Attempts Deleted */
            attempts_deleted: number;
            /** Practice Sessions Deleted */
            practice_sessions_deleted: number;
            /** Recordings Deleted */
            recordings_deleted: number;
            /** Settings Deleted */
            settings_deleted: number;
            /**
             * Cleared At
             * Format: date-time
             */
            cleared_at: string;
        };
        /** ConsistencyResponse */
        ConsistencyResponse: {
            /** Days */
            days: components["schemas"]["ActivityDay"][];
            /** Minutes */
            minutes: number;
            /** Problem Count */
            problem_count: number;
            /** Streak */
            streak: number;
            /** Best Streak */
            best_streak: number;
        };
        /**
         * DashboardRange
         * @description Windows the range selector offers, in days.
         *
         *     An IntEnum rather than a Literal: FastAPI hands query parameters to
         *     Pydantic as strings, and a Literal of ints refuses to coerce them, which
         *     made every explicit ?range_days= value fail validation.
         * @enum {integer}
         */
        DashboardRange: 30 | 60 | 90 | 180;
        /** DashboardResponse */
        DashboardResponse: {
            /** Attempt Count */
            attempt_count: number;
            /** Solved Count */
            solved_count: number;
            /** Logged Today */
            logged_today: number;
            /** Mastery Score */
            mastery_score: number;
            /** Readiness Score */
            readiness_score: number;
            /** Due Count */
            due_count: number;
            consistency: components["schemas"]["ConsistencyResponse"];
            /** Focuses */
            focuses: components["schemas"]["TopicFocusResponse"][];
            /** Review Queue */
            review_queue: components["schemas"]["ReviewQueueItem"][];
        };
        /**
         * Difficulty
         * @enum {string}
         */
        Difficulty: "easy" | "medium" | "hard";
        /** ExportAttempt */
        ExportAttempt: {
            /** Id */
            id: string;
            /** Problem Id */
            problem_id: number;
            /** Problem Title */
            problem_title: string;
            /** Problem Slug */
            problem_slug: string;
            /**
             * Completed At
             * Format: date-time
             */
            completed_at: string;
            /** Duration Seconds */
            duration_seconds: number;
            outcome: components["schemas"]["AttemptOutcome"];
            effort: components["schemas"]["AttemptEffort"];
            blocker: components["schemas"]["AttemptBlocker"];
            /** Notes */
            notes: string;
            /** Transcript */
            transcript: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ExportResponse */
        ExportResponse: {
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Attempts */
            attempts: components["schemas"]["ExportAttempt"][];
            /** Review State */
            review_state: components["schemas"]["ExportReviewState"][];
            prompt_templates: components["schemas"]["PromptTemplatesResponse"];
            interview_goals: components["schemas"]["InterviewGoalsResponse"];
        };
        /** ExportReviewState */
        ExportReviewState: {
            /** Problem Id */
            problem_id: number;
            /** Problem Title */
            problem_title: string;
            status: components["schemas"]["ProblemStatus"];
            /** Attempt Count */
            attempt_count: number;
            /** Best Duration Seconds */
            best_duration_seconds: number | null;
            /** Interval Days */
            interval_days: number;
            /** Lapses */
            lapses: number;
            /** Confidence */
            confidence: number;
            /** Due At */
            due_at: string | null;
        };
        /** FinalizePracticeSessionResponse */
        FinalizePracticeSessionResponse: {
            session: components["schemas"]["PracticeSessionResponse"];
            attempt: components["schemas"]["AttemptResponse"];
            /** Created */
            created: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
        };
        /** InterviewGoalsResponse */
        InterviewGoalsResponse: {
            /** Target Role */
            target_role: string;
            /** Target Date */
            target_date: string;
            /** Years Experience */
            years_experience: number | null;
        };
        /** InterviewGoalsUpdate */
        InterviewGoalsUpdate: {
            /**
             * Target Role
             * @default
             */
            target_role: string;
            /**
             * Target Date
             * @default
             */
            target_date: string;
            /** Years Experience */
            years_experience?: number | null;
        };
        /** JobResponse */
        JobResponse: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            status: components["schemas"]["JobStatus"];
            /** Attempts */
            attempts: number;
            /** Max Attempts */
            max_attempts: number;
            /**
             * Available At
             * Format: date-time
             */
            available_at: string;
            /** Lease Expires At */
            lease_expires_at: string | null;
            /** Error Code */
            error_code: string | null;
            /** Error Message */
            error_message: string | null;
            /** Completed At */
            completed_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * JobStatus
         * @enum {string}
         */
        JobStatus: "queued" | "processing" | "completed" | "failed" | "cancelled";
        /** LatestAttemptSummary */
        LatestAttemptSummary: {
            /** Id */
            id: string;
            /**
             * Completed At
             * Format: date-time
             */
            completed_at: string;
            /** Duration Seconds */
            duration_seconds: number;
            outcome: components["schemas"]["AttemptOutcome"];
            effort: components["schemas"]["AttemptEffort"];
            blocker: components["schemas"]["AttemptBlocker"];
        };
        /** PracticeSessionCreate */
        PracticeSessionCreate: {
            /** Problem Id */
            problem_id: number;
        };
        /** PracticeSessionFinalize */
        PracticeSessionFinalize: {
            /** Duration Seconds */
            duration_seconds?: number | null;
            outcome: components["schemas"]["AttemptOutcome"];
            effort: components["schemas"]["AttemptEffort"];
            /** @default none */
            blocker: components["schemas"]["AttemptBlocker"];
            /**
             * Notes
             * @default
             */
            notes: string;
        };
        /** PracticeSessionResponse */
        PracticeSessionResponse: {
            /** Id */
            id: string;
            /** Problem Id */
            problem_id: number;
            status: components["schemas"]["PracticeSessionStatus"];
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Running Since */
            running_since: string | null;
            /** Paused At */
            paused_at: string | null;
            /** Stopped At */
            stopped_at: string | null;
            /** Finalized At */
            finalized_at: string | null;
            /** Active Duration Ms */
            active_duration_ms: number;
            /** Attempt Id */
            attempt_id: string | null;
            recording: components["schemas"]["RecordingResponse"] | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * PracticeSessionStatus
         * @enum {string}
         */
        PracticeSessionStatus: "active" | "paused" | "awaiting_details" | "finalized" | "discarded";
        /**
         * ProblemAccess
         * @enum {string}
         */
        ProblemAccess: "all" | "free" | "premium";
        /** ProblemDetail */
        ProblemDetail: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Slug */
            slug: string;
            difficulty: components["schemas"]["Difficulty"];
            /** Premium */
            premium: boolean;
            /** Acceptance */
            acceptance: number;
            /** Active */
            active: boolean;
            /** Topics */
            topics: string[];
            status: components["schemas"]["ProblemStatus"];
            /** Attempt Count */
            attempt_count: number;
            last_attempt: components["schemas"]["LatestAttemptSummary"] | null;
            /** Best Duration Seconds */
            best_duration_seconds: number | null;
            /** Due At */
            due_at: string | null;
            /** Has Notes */
            has_notes: boolean;
            /** Has Audio */
            has_audio: boolean;
            /** Has Transcript */
            has_transcript: boolean;
            /** Catalog Updated At */
            catalog_updated_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ProblemListItem */
        ProblemListItem: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Slug */
            slug: string;
            difficulty: components["schemas"]["Difficulty"];
            /** Premium */
            premium: boolean;
            /** Acceptance */
            acceptance: number;
            /** Active */
            active: boolean;
            /** Topics */
            topics: string[];
            status: components["schemas"]["ProblemStatus"];
            /** Attempt Count */
            attempt_count: number;
            last_attempt: components["schemas"]["LatestAttemptSummary"] | null;
            /** Best Duration Seconds */
            best_duration_seconds: number | null;
            /** Due At */
            due_at: string | null;
            /** Has Notes */
            has_notes: boolean;
            /** Has Audio */
            has_audio: boolean;
            /** Has Transcript */
            has_transcript: boolean;
        };
        /** ProblemPage */
        ProblemPage: {
            /** Items */
            items: components["schemas"]["ProblemListItem"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
            /** Page Count */
            page_count: number;
        };
        /**
         * ProblemSort
         * @enum {string}
         */
        ProblemSort: "id-asc" | "id-desc" | "title-asc" | "title-desc" | "difficulty-asc" | "difficulty-desc" | "acceptance-asc" | "acceptance-desc";
        /**
         * ProblemStatus
         * @enum {string}
         */
        ProblemStatus: "not-started" | "solved" | "review" | "struggling";
        /** PromptTemplateUpdate */
        PromptTemplateUpdate: {
            /** Template */
            template: string;
        };
        /** PromptTemplatesResponse */
        PromptTemplatesResponse: {
            /** Session Template */
            session_template: string;
            /** Review Template */
            review_template: string;
        };
        /** ReadinessResponse */
        ReadinessResponse: {
            /**
             * Status
             * @default ready
             * @constant
             */
            status: "ready";
            /**
             * Database
             * @default ready
             * @constant
             */
            database: "ready";
        };
        /** RecordingResponse */
        RecordingResponse: {
            /** Id */
            id: string;
            /** Attempt Id */
            attempt_id: string | null;
            /** Practice Session Id */
            practice_session_id: string | null;
            /** Media Type */
            media_type: string;
            /** Byte Size */
            byte_size: number;
            /** Duration Ms */
            duration_ms: number;
            /** Checksum Sha256 */
            checksum_sha256: string;
            /** Content Url */
            content_url: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** RestoreRequest */
        RestoreRequest: {
            /** Filename */
            filename: string;
        };
        /** RestoreScheduledResponse */
        RestoreScheduledResponse: {
            /** Filename */
            filename: string;
            /** Will Restart */
            will_restart: boolean;
        };
        /** ReviewQueueItem */
        ReviewQueueItem: {
            /** Problem Id */
            problem_id: number;
            /** Title */
            title: string;
            /** Topic */
            topic: string;
            status: components["schemas"]["ProblemStatus"];
            /** Due In Days */
            due_in_days: number;
        };
        /** TopicFocusResponse */
        TopicFocusResponse: {
            /** Topic */
            topic: string;
            /** Score */
            score: number;
            /** Attempted */
            attempted: number;
            /** Problem Count */
            problem_count: number;
            /** Due Count */
            due_count: number;
        };
        /** TranscriptionCapability */
        TranscriptionCapability: {
            /** Enabled */
            enabled: boolean;
            /** Available */
            available: boolean;
            /** Model */
            model: string;
        };
        /** TranscriptionCorrection */
        TranscriptionCorrection: {
            /** Corrected Text */
            corrected_text: string;
        };
        /** TranscriptionResponse */
        TranscriptionResponse: {
            /** Id */
            id: string;
            /** Recording Id */
            recording_id: string;
            status: components["schemas"]["TranscriptionStatus"];
            /** Raw Text */
            raw_text: string | null;
            /** Corrected Text */
            corrected_text: string | null;
            /** Segments */
            segments: components["schemas"]["TranscriptionSegment"][];
            /** Language */
            language: string | null;
            /** Model */
            model: string | null;
            /** Retry Count */
            retry_count: number;
            /** Error Code */
            error_code: string | null;
            /** Error Message */
            error_message: string | null;
            /** Started At */
            started_at: string | null;
            /** Completed At */
            completed_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** TranscriptionSegment */
        TranscriptionSegment: {
            /** Start Seconds */
            start_seconds: number;
            /** End Seconds */
            end_seconds: number;
            /** Text */
            text: string;
        };
        /**
         * TranscriptionStatus
         * @enum {string}
         */
        TranscriptionStatus: "queued" | "processing" | "completed" | "failed";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    live_api_v1_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    ready_api_v1_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
        };
    };
    capabilities_api_v1_capabilities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapabilitiesResponse"];
                };
            };
        };
    };
    backup_status_api_v1_system_backups_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BackupStatusResponse"];
                };
            };
        };
    };
    backup_now_api_v1_system_backups_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BackupStatusResponse"];
                };
            };
        };
    };
    restore_backup_api_v1_system_backups_restore_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RestoreRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestoreScheduledResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    backup_files_api_v1_system_backups_files_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BackupFileListResponse"];
                };
            };
        };
    };
    remove_backup_api_v1_system_backups_files__filename__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                filename: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BackupFileListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    prompt_templates_api_v1_settings_prompt_templates_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptTemplatesResponse"];
                };
            };
        };
    };
    save_prompt_template_api_v1_settings_prompt_templates__template_key__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PromptTemplateUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptTemplatesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_saved_prompt_template_api_v1_settings_prompt_templates__template_key__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptTemplatesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    interview_goals_api_v1_settings_interview_goals_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterviewGoalsResponse"];
                };
            };
        };
    };
    save_interview_goals_api_v1_settings_interview_goals_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InterviewGoalsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterviewGoalsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_data_api_v1_system_export_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportResponse"];
                };
            };
        };
    };
    clear_data_api_v1_system_clear_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClearResponse"];
                };
            };
        };
    };
    problems_api_v1_problems_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                search?: string | null;
                difficulty?: components["schemas"]["Difficulty"] | null;
                status?: components["schemas"]["ProblemStatus"] | null;
                access?: components["schemas"]["ProblemAccess"];
                topic?: string | null;
                sort?: components["schemas"]["ProblemSort"];
                include_inactive?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    problem_api_v1_problems__problem_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                problem_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_attempts_api_v1_attempts_get: {
        parameters: {
            query?: {
                problem_id?: number | null;
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttemptListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_problem_attempts_api_v1_problems__problem_id__attempts_get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
            };
            header?: never;
            path: {
                problem_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttemptListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_problem_attempt_api_v1_problems__problem_id__attempts_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                problem_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttemptCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttemptResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_attempt_api_v1_attempts__attempt_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attempt_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttemptResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_attempt_api_v1_attempts__attempt_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attempt_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_attempt_api_v1_attempts__attempt_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attempt_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttemptUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttemptResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_attempt_recording_api_v1_attempts__attempt_id__recording_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attempt_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_api_v1_catalog_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogSyncResponse"];
                };
            };
        };
    };
    read_dashboard_api_v1_dashboard_get: {
        parameters: {
            query?: {
                range_days?: components["schemas"]["DashboardRange"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_queue_api_v1_review_queue_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewQueueItem"][];
                };
            };
        };
    };
    read_api_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_api_v1_practice_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PracticeSessionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PracticeSessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    current_api_v1_practice_sessions_current_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PracticeSessionResponse"] | null;
                };
            };
        };
    };
    pause_api_v1_practice_sessions__session_id__pause_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PracticeSessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_api_v1_practice_sessions__session_id__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PracticeSessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_api_v1_practice_sessions__session_id__stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["Body_stop_api_v1_practice_sessions__session_id__stop_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PracticeSessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    finalize_api_v1_practice_sessions__session_id__finalize_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PracticeSessionFinalize"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FinalizePracticeSessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    discard_api_v1_practice_sessions__session_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    content_api_v1_recordings__recording_id__content_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recording_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_api_v1_attempts__attempt_id__transcription_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attempt_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranscriptionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_api_v1_attempts__attempt_id__transcription_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attempt_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranscriptionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    correct_api_v1_attempts__attempt_id__transcription_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attempt_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TranscriptionCorrection"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranscriptionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_api_v1_attempts__attempt_id__transcription_retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                attempt_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranscriptionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
