/**
 * Generated by `npm run generate:api` from FastAPI's OpenAPI document.
 *
 * This checked-in bootstrap keeps the frontend buildable before the first API
 * container is running; the generator replaces it with the complete contract.
 */
export interface paths {
  [path: string]: Record<string, unknown>
}
